import type { LegacyUpgradeDef, MemberTierDef, RacketDef } from "./types";

export const RACKETS: RacketDef[] = [
  {
    id: "scrapyard",
    name: "Scrap Yard",
    flavor: "Strip it, sell it, don't ask questions.",
    icon: "scrapyard",
    baseCost: 10,
    baseIncome: 0.5,
    costGrowth: 1.14,
  },
  {
    id: "chopshop",
    name: "Chop Shop",
    flavor: "Yesterday's stolen ride, today's spare parts.",
    icon: "chopshop",
    baseCost: 120,
    baseIncome: 4,
    costGrowth: 1.145,
    requires: "scrapyard",
  },
  {
    id: "paint",
    name: "Custom Paint Booth",
    flavor: "Flames, skulls, and a fresh coat of trouble.",
    icon: "paint",
    baseCost: 1400,
    baseIncome: 38,
    costGrowth: 1.15,
    requires: "chopshop",
  },
  {
    id: "bar",
    name: "The Rusty Chain",
    flavor: "The clubhouse bar. Whiskey and loyalty on tap.",
    icon: "bar",
    baseCost: 16000,
    baseIncome: 360,
    costGrowth: 1.15,
    requires: "paint",
  },
  {
    id: "tattoo",
    name: "Ink & Iron Tattoo",
    flavor: "Earn your patch, then earn the ink.",
    icon: "tattoo",
    baseCost: 190000,
    baseIncome: 3800,
    costGrowth: 1.155,
    requires: "bar",
  },
  {
    id: "poker",
    name: "Back Room Poker",
    flavor: "The house always wins. The club is the house.",
    icon: "poker",
    baseCost: 2300000,
    baseIncome: 42000,
    costGrowth: 1.155,
    requires: "tattoo",
  },
  {
    id: "smuggling",
    name: "Border Runs",
    flavor: "Fast bikes, quiet roads, big payouts.",
    icon: "smuggling",
    baseCost: 28000000,
    baseIncome: 480000,
    costGrowth: 1.16,
    requires: "poker",
  },
  {
    id: "speedway",
    name: "Underground Speedway",
    flavor: "Illegal races. Legendary purses.",
    icon: "speedway",
    baseCost: 340000000,
    baseIncome: 5600000,
    costGrowth: 1.16,
    requires: "smuggling",
  },
];

export const LEGACY_UPGRADES: LegacyUpgradeDef[] = [
  {
    id: "chrome_plating",
    name: "Chrome Plating",
    flavor: "Every rig in the yard gleams. Respect follows shine.",
    effect: "income",
    valuePerLevel: 0.1,
    baseCost: 1,
    costGrowth: 1.35,
    maxLevel: 50,
  },
  {
    id: "reputation",
    name: "Street Reputation",
    flavor: "Word travels fast. Recruits line up cheaper.",
    effect: "recruitCost",
    valuePerLevel: 0.03,
    baseCost: 1,
    costGrowth: 1.4,
    maxLevel: 25,
  },
  {
    id: "road_captain",
    name: "Road Captain's Network",
    flavor: "Faster routes, bigger scores, no wasted miles.",
    effect: "income",
    valuePerLevel: 0.18,
    baseCost: 3,
    costGrowth: 1.45,
    maxLevel: 20,
  },
  {
    id: "nest_egg",
    name: "Nest Egg",
    flavor: "Every new chapter starts with cash in the saddlebag.",
    effect: "startCash",
    valuePerLevel: 2500,
    baseCost: 2,
    costGrowth: 1.3,
    maxLevel: 30,
  },
];

export const MEMBER_INCOME_BONUS = 0.02;
export const MEMBER_AUTO_RATE = 0.1;
export const CLICK_BONUS_FLOOR = 10;
export const CLICK_BONUS_INCOME_SHARE = 0.6;
export const OFFLINE_CAP_SECONDS = 4 * 60 * 60;
export const OFFLINE_EFFICIENCY = 0.5;

export const MEMBER_TIERS: MemberTierDef[] = [
  {
    id: "prospect",
    name: "Prospect",
    flavor: "Washing bikes and earning trust. Everyone starts here.",
    icon: "patch",
    baseCost: 50,
    costGrowth: 1.13,
    weight: 1,
  },
  {
    id: "patched",
    name: "Patched Member",
    flavor: "Earned the colors. Brings in prospects on their own.",
    icon: "patch",
    baseCost: 2000,
    costGrowth: 1.14,
    weight: 20,
    requires: "prospect",
  },
  {
    id: "road_captain",
    name: "Road Captain",
    flavor: "Runs the recruiting routes, chapter to chapter.",
    icon: "officer",
    baseCost: 100000,
    costGrowth: 1.15,
    weight: 400,
    requires: "patched",
  },
  {
    id: "sergeant",
    name: "Sergeant at Arms",
    flavor: "Keeps the peace, keeps the ranks growing.",
    icon: "officer",
    baseCost: 6000000,
    costGrowth: 1.16,
    weight: 8000,
    requires: "road_captain",
  },
  {
    id: "vice_president",
    name: "Vice President",
    flavor: "Second in command, building the bench.",
    icon: "officer",
    baseCost: 400000000,
    costGrowth: 1.17,
    weight: 160000,
    requires: "sergeant",
  },
  {
    id: "chapter_president",
    name: "Chapter President",
    flavor: "Runs the chapter. Every rider answers to them.",
    icon: "officer",
    baseCost: 32000000000,
    costGrowth: 1.18,
    weight: 3200000,
    requires: "vice_president",
  },
  {
    id: "national_president",
    name: "National President",
    flavor: "The name on every chapter's charter.",
    icon: "officer",
    baseCost: 3000000000000,
    costGrowth: 1.19,
    weight: 64000000,
    requires: "chapter_president",
  },
];
