import type { ChapterDef, LegacyUpgradeDef, MemberTierDef, RacketDef } from "./types";

export const RACKETS: RacketDef[] = [
  {
    id: "scrapyard",
    name: "Scrap Yard",
    flavor: "Strip it, sell it, don't ask questions.",
    icon: "scrapyard",
    baseCost: 10,
    baseIncome: 0.5,
    costGrowth: 1.14,
  },
  {
    id: "chopshop",
    name: "Chop Shop",
    flavor: "Yesterday's stolen ride, today's spare parts.",
    icon: "chopshop",
    baseCost: 120,
    baseIncome: 4,
    costGrowth: 1.145,
    requires: "scrapyard",
  },
  {
    id: "paint",
    name: "Custom Paint Booth",
    flavor: "Flames, skulls, and a fresh coat of trouble.",
    icon: "paint",
    baseCost: 1400,
    baseIncome: 38,
    costGrowth: 1.15,
    requires: "chopshop",
  },
  {
    id: "bar",
    name: "The Rusty Chain",
    flavor: "The clubhouse bar. Whiskey and loyalty on tap.",
    icon: "bar",
    baseCost: 16000,
    baseIncome: 360,
    costGrowth: 1.15,
    requires: "paint",
  },
  {
    id: "tattoo",
    name: "Ink & Iron Tattoo",
    flavor: "Earn your patch, then earn the ink.",
    icon: "tattoo",
    baseCost: 190000,
    baseIncome: 3800,
    costGrowth: 1.155,
    requires: "bar",
  },
  {
    id: "poker",
    name: "Back Room Poker",
    flavor: "The house always wins. The club is the house.",
    icon: "poker",
    baseCost: 2300000,
    baseIncome: 42000,
    costGrowth: 1.155,
    requires: "tattoo",
  },
  {
    id: "smuggling",
    name: "Border Runs",
    flavor: "Fast bikes, quiet roads, big payouts.",
    icon: "smuggling",
    baseCost: 28000000,
    baseIncome: 480000,
    costGrowth: 1.16,
    requires: "poker",
  },
  {
    id: "speedway",
    name: "Underground Speedway",
    flavor: "Illegal races. Legendary purses.",
    icon: "speedway",
    baseCost: 340000000,
    baseIncome: 5600000,
    costGrowth: 1.16,
    requires: "smuggling",
  },
];

export const RACKET_MILESTONES = [10, 25, 50, 100, 200];
export const RACKET_MILESTONE_BONUS = 2;
export const RACKET_MILESTONE_COST_MULTIPLIER = 10;

export const LEGACY_UPGRADES: LegacyUpgradeDef[] = [
  {
    id: "chrome_plating",
    name: "Chrome Plating",
    flavor: "Every rig in the yard gleams. Respect follows shine.",
    effect: "income",
    valuePerLevel: 0.1,
    baseCost: 1,
    costGrowth: 1.35,
    maxLevel: 50,
  },
  {
    id: "reputation",
    name: "Street Reputation",
    flavor: "Word travels fast. Recruits line up cheaper.",
    effect: "recruitCost",
    valuePerLevel: 0.03,
    baseCost: 1,
    costGrowth: 1.4,
    maxLevel: 25,
  },
  {
    id: "road_captain",
    name: "Road Captain's Network",
    flavor: "Faster routes, bigger scores, no wasted miles.",
    effect: "income",
    valuePerLevel: 0.18,
    baseCost: 3,
    costGrowth: 1.45,
    maxLevel: 20,
  },
  {
    id: "nest_egg",
    name: "Nest Egg",
    flavor: "Every new chapter starts with cash in the saddlebag.",
    effect: "startCash",
    valuePerLevel: 2500,
    baseCost: 2,
    costGrowth: 1.3,
    maxLevel: 30,
  },
];

export const MEMBER_INCOME_BONUS = 0.02;
export const MEMBER_AUTO_RATE = 0.1;
export const CLICK_BONUS_FLOOR = 10;
export const CLICK_BONUS_INCOME_SHARE = 0.6;
export const OFFLINE_CAP_SECONDS = 4 * 60 * 60;
export const OFFLINE_EFFICIENCY = 0.5;

export const MEMBER_TIERS: MemberTierDef[] = [
  {
    id: "prospect",
    name: "Prospect",
    flavor: "Washing bikes and earning trust. Everyone starts here.",
    icon: "patch",
    baseCost: 50,
    costGrowth: 1.13,
    weight: 1,
  },
  {
    id: "patched",
    name: "Patched Member",
    flavor: "Earned the colors. Brings in prospects on their own.",
    icon: "patch",
    baseCost: 2000,
    costGrowth: 1.14,
    weight: 20,
  },
  {
    id: "road_captain",
    name: "Road Captain",
    flavor: "Runs the recruiting routes, chapter to chapter.",
    icon: "officer",
    baseCost: 100000,
    costGrowth: 1.15,
    weight: 400,
  },
  {
    id: "sergeant",
    name: "Sergeant at Arms",
    flavor: "Keeps the peace, keeps the ranks growing.",
    icon: "officer",
    baseCost: 6000000,
    costGrowth: 1.16,
    weight: 8000,
  },
  {
    id: "vice_president",
    name: "Vice President",
    flavor: "Second in command, building the bench.",
    icon: "officer",
    baseCost: 400000000,
    costGrowth: 1.17,
    weight: 160000,
  },
  {
    id: "chapter_president",
    name: "Chapter President",
    flavor: "Runs the chapter. Every rider answers to them.",
    icon: "officer",
    baseCost: 32000000000,
    costGrowth: 1.18,
    weight: 3200000,
  },
  {
    id: "national_president",
    name: "National President",
    flavor: "The name on every chapter's charter.",
    icon: "officer",
    baseCost: 3000000000000,
    costGrowth: 1.19,
    weight: 64000000,
  },
];

/**
 * City/road layout for the fictional route map (an invented landmass, not the
 * real world). Coordinates live in an SVG viewBox of "0 0 340 950", laid out
 * as a zigzag snaking south so the route reads top-to-bottom on a mobile
 * viewport. Order in this array is the unlock order — the route is strictly
 * linear, city N+1 always comes right after city N.
 */
export const CHAPTERS: ChapterDef[] = [
  {
    id: "rust_hollow",
    name: "Rust Hollow",
    region: "Rust Belt",
    flavor: "Shuttered mills and cheap gas. Nobody asks questions here.",
    bikeName: "Rust Hollow Bobber",
    unlockCost: 10,
    bonus: 0.05,
    accent: "#d9662b",
    patch: "gear",
    unlocksTier: "patched",
    mapX: 90,
    mapY: 70,
  },
  {
    id: "salt_flats",
    name: "Salt Flats",
    region: "Desert Southwest",
    flavor: "Flat, white, and endless. Built for opening the throttle.",
    bikeName: "Salt Flats Chopper",
    unlockCost: 75,
    bonus: 0.05,
    accent: "#e4b243",
    patch: "sun",
    unlocksTier: "road_captain",
    mapX: 250,
    mapY: 180,
  },
  {
    id: "pine_ridge",
    name: "Pine Ridge",
    region: "Pacific Northwest",
    flavor: "Switchbacks through the timber, rain or shine.",
    bikeName: "Pine Ridge Enduro",
    unlockCost: 500,
    bonus: 0.05,
    accent: "#5a8a5a",
    patch: "pine",
    unlocksTier: "sergeant",
    mapX: 90,
    mapY: 290,
  },
  {
    id: "bayou_crossing",
    name: "Bayou Crossing",
    region: "Deep South",
    flavor: "Humid nights, slow water, and a clubhouse on stilts.",
    bikeName: "Bayou Crossing Cruiser",
    unlockCost: 4000,
    bonus: 0.05,
    accent: "#4a8a94",
    patch: "moon",
    unlocksTier: "vice_president",
    mapX: 250,
    mapY: 400,
  },
  {
    id: "copper_canyon",
    name: "Copper Canyon",
    region: "Southwest Mesa",
    flavor: "Switchback roads carved into red rock.",
    bikeName: "Copper Canyon Scrambler",
    unlockCost: 30000,
    bonus: 0.05,
    accent: "#b5651d",
    patch: "mesa",
    unlocksTier: "chapter_president",
    mapX: 90,
    mapY: 510,
  },
  {
    id: "steel_harbor",
    name: "Steel Harbor",
    region: "Coastal Port",
    flavor: "Shipping cranes and salt air. Freight moves both ways.",
    bikeName: "Steel Harbor Cafe Racer",
    unlockCost: 200000,
    bonus: 0.05,
    accent: "#7d8c99",
    patch: "anchor",
    unlocksTier: "national_president",
    mapX: 250,
    mapY: 620,
  },
  {
    id: "wildfire_mesa",
    name: "Wildfire Mesa",
    region: "High Desert Badlands",
    flavor: "Scorched earth and open highway to the horizon.",
    bikeName: "Wildfire Mesa Streetfighter",
    unlockCost: 1000000,
    bonus: 0.2,
    accent: "#a3222b",
    patch: "flame",
    mapX: 90,
    mapY: 730,
  },
  {
    id: "vultures_rest",
    name: "Vulture's Rest",
    region: "National Chapter",
    flavor: "Where it all started. Every road leads back here.",
    bikeName: "Vulture's Rest Road King",
    unlockCost: 5000000,
    bonus: 0.3,
    accent: "#8a5aa0",
    patch: "wings",
    mapX: 250,
    mapY: 840,
  },
];

export const CHAPTER_MAP_VIEWBOX = { width: 340, height: 950 };
